version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresPrep
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
